### ISSUE TITLE
Unable to download reports

### ISSUE THREAD

**Issue by Unit981** [factionsecurity/faction#59]
I have recently redeployed a faction server and I can't seem to download my reports.
I've tried to download sample reports and custom reports, default template and custom template - all to no avail. 
The image below demonstrates that my report is showing as successfully generated, however when i click download - it opens a new tab and does not download anything.

Screenshot also shows version number
![image](https://github.com/factionsecurity/faction/assets/104841370/3495d940-8fc9-4e16-8eb0-1530f8287b1d)

To confirm that it wasn't a simple case of 'PEBKAC', I've redeployed on both 2 separate VPS's and locally in VM's - the issue replicates every time.

**Comment by summitt** [comment]
Can you confirm that you have a report that matches the Team and Assessment Type of the Assessment?

For instance, if you click edit in the assessment it may look something like this:
![image](https://github.com/factionsecurity/faction/assets/2343831/1de34885-c741-4a08-837d-060f5fafd71c)

Then ensure you have a report template in the Report Designer that matches as shown below:

![image](https://github.com/factionsecurity/faction/assets/2343831/d4fe1081-32c5-4011-bc51-819e372c2315)

**Comment by Unit981** [comment]
> Can you confirm that you have a report that matches the Team and Assessment Type of the Assessment?
> 
> For instance, if you click edit in the assessment it may look something like this: ![image](https://private-user-images.githubusercontent.com/2343831/339880199-1de34885-c741-4a08-837d-060f5fafd71c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODIzNzAsIm5iZiI6MTcxODY4MjA3MCwicGF0aCI6Ii8yMzQzODMxLzMzOTg4MDE5OS0xZGUzNDg4NS1jNzQxLTRhMDgtODM3ZC0wNjBmNWZhZmQ3MWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDM0MTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzVmYmY2Yzk4NDFlNTMzY2UxYTY4YmJjMjZhMGFiODIyMzM3OThhZTBhM2Y1YThmMzM1NDI3YjVhOWM5NmM5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.62HIn2v5PkA4mtZ2f_HutZrNF6bWIYZ24OPTQl6jABg)
> 
> Then ensure you have a report template in the Report Designer that matches as shown below:
> 
> ![image](https://private-user-images.githubusercontent.com/2343831/339880312-d4fe1081-32c5-4011-bc51-819e372c2315.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODIzNzAsIm5iZiI6MTcxODY4MjA3MCwicGF0aCI6Ii8yMzQzODMxLzMzOTg4MDMxMi1kNGZlMTA4MS0zMmM1LTQwMTEtYmM1MS04MTllMzcyYzIzMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMDM0MTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjdkZmMzZTNmZWQ3MWE2NWE0Y2M3ZDE3MDI3N2YyYTBiNzUyNzg1ZTQyMWUzYzdkYzM2NGIzMTFiNGYzNGNkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zIq5yHhT_JHvWl_uuKeiRNeatbAOkSlNxCaVwpft7y4)

Hi @summitt  - confirming that I have got the correct details matching up, the team name and report templates are matching to those seen inside Report Designer.

**Comment by summitt** [comment]
Would you mind trying to upload a new template from here: https://github.com/factionsecurity/report_templates. 

Maybe the default template got corrupted somehow.

**Comment by Unit981** [comment]
Hi @summitt - Just tried this and found the issue persists (even after regenerating report). I tried the 2 report templates available at the link provided above.

I think that my multiple redeployments of faction would rule this out as being an issue anyway.

**Comment by summitt** [comment]
Is there anything in the logs that indicate an error (catalina.out).

**Comment by summitt** [comment]
@Unit981 The other thing might be the memory in your VMs. Can you confirm how much memory is available?

**Comment by summitt** [comment]
@Unit981 There has been another issue reported (#61) that may be the same issue you experienced. This has been fixed in july24-updates branch. It's part of a bunch a fixes and ui updates that will be released to main in a few weeks. 

If you have the cycles check out the july24-updates branch and see if this fixes your issue.

**Comment by eLcapitanoBD** [comment]
The issue still persists. Is it possible to get a proper solution soon?

**Comment by summitt** [comment]
@eLcapitanoBD are you also using the default templates and it fails on report generation?

**Comment by summitt** [comment]
Closing this issue because lacking information to reproduce.
